-- MySQL Script generated by MySQL Workbench
-- Fri Apr 28 15:41:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poqutec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poqutec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poqutec` DEFAULT CHARACTER SET utf8 ;
USE `poqutec` ;

-- -----------------------------------------------------
-- Table `poqutec`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`position` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`position` (
  `id` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`country` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`country` (
  `id` INT NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`type` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`company` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`company` (
  `id` INT NOT NULL,
  `company` VARCHAR(150) NOT NULL,
  `web` VARCHAR(150) NULL,
  `tel` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `main_email` VARCHAR(150) NULL,
  `address` VARCHAR(200) NULL,
  `registed_at` TIMESTAMP NOT NULL,
  `country_id` INT NULL,
  `type_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_company_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `poqutec`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `poqutec`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`person` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`person` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `registed_at` TIMESTAMP NOT NULL,
  `position_id` INT NULL,
  `company_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_person_position`
    FOREIGN KEY (`position_id`)
    REFERENCES `poqutec`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `poqutec`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`account` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`account` (
  `id` INT NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `registed_at` TIMESTAMP NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_account_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `poqutec`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`category` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`category` (
  `id` INT NOT NULL,
  `category` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`product` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`product` (
  `id` INT NOT NULL,
  `product` VARCHAR(50) NOT NULL,
  `price` FLOAT NULL,
  `remark` TEXT NULL,
  `registed_at` TIMESTAMP NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `poqutec`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`company_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`company_category` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`company_category` (
  `id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `company_id`),
  CONSTRAINT `fk_company_product_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `poqutec`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_product_category_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `poqutec`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`payment_term`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`payment_term` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`payment_term` (
  `id` INT NOT NULL,
  `payment_term` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`incoterm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`incoterm` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`incoterm` (
  `id` INT NOT NULL,
  `incoterm` VARCHAR(45) NOT NULL,
  `incoterm_short` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`inquiry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`inquiry` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`inquiry` (
  `id` INT NOT NULL,
  `registed_at` TIMESTAMP NOT NULL,
  `company_id` INT NOT NULL,
  `payment_term_id` INT NOT NULL,
  `incoterm_id` INT NOT NULL,
  PRIMARY KEY (`id`, `payment_term_id`, `incoterm_id`),
  CONSTRAINT `fk_inquiry_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `poqutec`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquiry_payment_term1`
    FOREIGN KEY (`payment_term_id`)
    REFERENCES `poqutec`.`payment_term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquiry_incoterm1`
    FOREIGN KEY (`incoterm_id`)
    REFERENCES `poqutec`.`incoterm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`inquiry_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`inquiry_product` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`inquiry_product` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `inquiry_id` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`, `product_id`, `inquiry_id`),
  CONSTRAINT `fk_inquiry_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `poqutec`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquiry_product_inquiry1`
    FOREIGN KEY (`inquiry_id`)
    REFERENCES `poqutec`.`inquiry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`sale` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`sale` (
  `id` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `registed_at` TIMESTAMP NOT NULL,
  `inquiry_id` INT NOT NULL,
  PRIMARY KEY (`id`, `inquiry_id`),
  CONSTRAINT `fk_sale_inquiry1`
    FOREIGN KEY (`inquiry_id`)
    REFERENCES `poqutec`.`inquiry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poqutec`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poqutec`.`payment` ;

CREATE TABLE IF NOT EXISTS `poqutec`.`payment` (
  `id` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `registed_at` TIMESTAMP NOT NULL,
  `sale_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sale_id`),
  CONSTRAINT `fk_payment_sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `poqutec`.`sale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
